handys/handys/urls.py
from django.contrib import admin
from django.urls import path, include

from main_site.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_site.urls')),
]
handler404 = pageNotFound

handys/main_site/urls.py
from .views import *
from django.urls import path
from django.contrib.sitemaps import Sitemap #class for sitemap creating
from django.contrib.sitemaps.views import sitemap #view_function for sitemap creating

#creating Class and dict for sitemap
class BlogSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        return Smartphones.objects.filter(is_published=True)

sitemaps = {'blog': BlogSitemap}
#####

urlpatterns = [
    path('', index, name='home'),
    path('post/<slug:slug_adress>', viewpost, name='post'),
    path('category/<int:cat_id>', view_category, name='category'),
    path('page/<int:number>', other_page, name='other page'),
    path('tag/<str:query>', tags, name='tags'),
    path('registration/', registragion, name='registration'),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap")
]

handys/main_site/models.py
from django.db import models
from django.urls import reverse
import json

class Smartphones(models.Model):
    post_title = models.CharField(max_length=255)
    post_content = models.TextField()
    slug = models.SlugField(unique=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    changing_date = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)
    image = models.CharField(max_length=255, null=True)
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, default=1)
    tags = models.CharField(max_length=1000, default='[]')

    def get_tags(self):
        tags = self.tags
        return json.loads(tags)

    def set_tags(self, arg):
        self.tags = arg




    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse('post', kwargs={'slug_adress': self.slug})

    class Meta():
        verbose_name = 'Смартфоны'
        verbose_name_plural = 'Смартфоны'
        ordering = ('id',)

class Tags(models.Model):
    tag_name = models.CharField(max_length=255)

    def __str__(self):
        return self.tag_name

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_id': self.pk})

    class Meta():
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

handys/main_site/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Category, Smartphones
from django.core.exceptions import ValidationError

class AddPostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = 'Категория не выбрана'


    class Meta():
        model = Smartphones
        fields = ['post_title', 'post_content', 'slug', 'cat']
        widgets = {
            'post_content': forms.Textarea(attrs={'cols': 60, 'rows': 10})
        }

    def clean_post_title(self):
        title = self.cleaned_data['post_title']
        if len(title)>200:
            raise ValidationError('Длина заголовка слишком большая')

class UserRegister(UserCreationForm):
    username = forms.CharField(label='Имя', widget=forms.TextInput())
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput())

handys/main_site/views.py
import json

from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.db.models import Q
from random import shuffle
import re
from main_site.forms import *
from main_site.models import Smartphones, Category, Tags
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator


def index(request):
    current_page_number = request.GET.get('page')
    if current_page_number == '1':
        return redirect('home')
    if current_page_number is None:
        current_page_number = 1
    current_page_number = int(current_page_number)
    all_posts = Smartphones.objects.all()
    categories = Category.objects.all()

    paginator = Paginator(all_posts, 9)
    current_page = paginator.page(current_page_number)
    posts = current_page.object_list
    previous_page_number = current_page_number - 1
    pre_previous_page_number = current_page_number - 2
    next_page_number = current_page_number + 1
    next_next_page_number = current_page_number + 2
    pagination = [pre_previous_page_number, previous_page_number, current_page_number, next_page_number,
                  next_next_page_number]

    context = {
        'posts': posts,
        'categories': categories,
        'current_page': current_page_number,
        'pagination': pagination,
        'last_page': paginator.num_pages
    }
    return render(request, 'main_site/index.html', context=context)







def viewpost(request, slug_adress):
    content = Smartphones.objects.get(slug=slug_adress)
    title = content.post_title
    tags = eval(content.tags)
    tag1 = tags[0]
    tag2 = tags[1]
    all_tags = Tags.objects.all()
    similar = Smartphones.objects.filter(Q(post_title__contains=tag1) | Q(post_title__contains=tag2)).order_by('?')
    #similar = Smartphones.objects.filter(Q(tags__contains=tag1) | Q(tags__contains=tag2)).order_by('?')

    similar = similar[:12]
    context = {
        'content': content,
        'tag1': tag1,
        'tag2': tag2,
        'similar': similar,
        'all_tags': all_tags
    }
    return render(request, 'main_site/post.html', context=context)

def view_category(request, cat_id):
    current_page_number = request.GET.get('page')
    if current_page_number == '1':
        return redirect(f'/category/{cat_id}')
    if current_page_number is None:
        current_page_number = 1
    else:
        current_page_number = int(current_page_number)
    categories = Category.objects.all()
    all_posts = Smartphones.objects.filter(cat_id=cat_id)

    #Pagination
    paginator = Paginator(all_posts, 9)
    current_page = paginator.page(current_page_number)
    posts = current_page.object_list
    previous_page_number = current_page_number-1
    pre_previous_page_number = current_page_number-2
    next_page_number = current_page_number+1
    next_next_page_number = current_page_number+2
    pagination = [pre_previous_page_number, previous_page_number, current_page_number, next_page_number, next_next_page_number]

    if cat_id>len(categories):
        return Http404(request, 'не найдено')
    context = {
            'categories': categories,
            'current_category': cat_id,
            'current_page': current_page_number,
            'all_posts': posts,
            'pagination': pagination,
            'last_page': paginator.num_pages
            }

    return render(request, 'main_site/category.html', context=context)

def other_page(request, number):
    if number == 1:
        return redirect('home')
    num = (number-1)*10-(number-1)
    num_to = num+9
    posts = Smartphones.objects.all()[num:num_to]
    pattern = r'<img src="(.*?)"'
    images = dict()
    for post in posts:
        content = post.post_content
        image = re.search(pattern, content)
        if image:
            images[post.slug] = image.group(1).replace('"', '')
        else:
            images[
                post.slug] = 'https://fdn.gsmarena.com/imgroot/reviews/23/vivo-v27/lifestyle/-1200w5/gsmarena_017.jpg'

    context = {
        'posts': posts,
        'current_category': 0,
        'categories': Category.objects.all(),
        'images': images,
        'current_page': number
    }
    return render(request, 'main_site/other.html', context=context)

def other_page_cats(request, cat_id, number):
    if number == 1:
        posts = Smartphones.objects.filter(cat_id=cat_id)[:9]
    else:
        num = (number-1)*10-(number-1)
        num_to = num+9
        posts = Smartphones.objects.filter(cat_id=cat_id)[num:num_to]
    pattern = r'<img src="(.*?)"'
    images = dict()
    for post in posts:
        content = post.post_content
        image = re.search(pattern, content)
        if image:
            images[post.slug] = image.group(1).replace('"', '')
        else:
            images[
                post.slug] = 'https://fdn.gsmarena.com/imgroot/reviews/23/vivo-v27/lifestyle/-1200w5/gsmarena_017.jpg'

    context = {
        'posts': posts,
        'current_category': cat_id,
        'categories': Category.objects.all(),
        'images': images,
        'current_page': number
    }
    return render(request, 'main_site/other.html', context=context)

def tags(request, query):
    query = query.replace('%20', ' ')
    all_posts = Smartphones.objects.filter(post_title__icontains=query)
    context = {
        'all_posts': all_posts,
        'tag': query
    }
    return render(request, 'main_site/tag.html', context=context)

def registragion(request):
    form = UserRegister
    context = {
        'registragion_form': form
    }
    return render(request, 'main_site/registration.html', context=context)

def creating_tags(request):
    all_posts = Smartphones.objects.all()
    for post in all_posts:
        title = post.post_title
        try:
            if ':' in title:
                phone1 = title.split(':')[0].split(' vs ')[0]
                phone2 = title.split(':')[0].split(' vs ')[1]
                post.tags = [phone1, phone2]
                post.save()
                continue
            if '.' in title:
                phone1 = title.split('.')[0].split(' vs ')[0]
                phone2 = title.split('.')[0].split(' vs ')[1]
                post.tags = [phone1, phone2]
                post.save()
        except:
            continue

    return HttpResponse('Готово')
def pageNotFound(request, exception):
    return HttpResponseNotFound(f'<h1>Страница не найдена</h1>'
                                f'{exception}')

handys/main_site/templates/main_site/add_post.html
{% extends 'main_site/base.html' %}

{% block main_content_on_the_page %}
    <form action="{% url 'add_post' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Подтвердить</button>
    </form>

{% endblock main_content_on_the_page %}

handys/main_site/templates/main_site/base.html
{% load static %}
{% load posts_smartphones %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="{% static 'main_site/css/mycss.css' %}" rel="stylesheet" type="text/css" >
    <link rel="shortcut icon" type="image/icon" href="{% static 'main_site/images/favicon.ico' %}" >



    {%block title%}
    {%endblock title%}
</head>

<body>
    <conteiner-fluid>
        <div class="main-block">
            <div class="menu">
                <div class="conteiner">
                    <div class="row">
                        <div class="col-sm-1 none-block">
                        </div>
                        <div class="col-sm-11 secondary-menu">
                            <ol>
                                <li><a href="/"><button type="button" class="btn btn-outline-secondary">Haupt seite</button></a></li>
                                {%if categories%}
                                    {%for cat in categories%}
                                        {%if current_category == cat.id%}
                                            <li><button type="button" class="btn btn-secondary">{{cat.name}}</button></li>
                                        {% else %}
                                            <li><a href="{{cat.get_absolute_url}}"><button type="button"
                                                    class="btn btn-outline-secondary">{{cat.name}}</button></a></li>
                                        {% endif %}
                                    {%endfor%}
                                {%else%}
                                    {% category_list current_category=current_category %}
                                {%endif%}
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="conteiner haupt">
                <div class="row">
                    <div class="col-sm-1">
                    </div>
                    <div class="col-sm-7 main-block">
                        {% block main_content_on_the_page %}
                        {% endblock main_content_on_the_page %}
                    </div>
                    <div class="col-md-3 right-column">
                        <div class="card" style="width: 18rem;">
                            <div class="card-header">
                                Letzten Posten
                            </div>
                            <ul class="list-group list-group-flush">
                            {% all_posts_ as all %}
                            {%for post in all%}
                                {% if post.is_published == True %}
                                    
                                    <li class="list-group-item"><a href="/post/{{post.slug}}">{{post.post_title}}</a></li>

                                {% endif %}
                            {%endfor%}
                            </ul>
                        </div>
                        {%block content_in_right_column%}
                        {%endblock content_in_right_column%}
                    </div>
                </div>
                
            </div>
            <div class="footer_">
                <span>Alle Posten wurden von ChatGPT ausgearbeitet</span>
            </div>
        </div>
    </conteiner-fluid>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>

</body>

</html>

handys/main_site/templates/main_site/category.html
{% extends 'main_site/base.html' %}
{% load posts_smartphones %}

{%block title%}
    <title>Die Vergleiche der Handys - seite {{current_page}}</title>
{%endblock%}

{% block main_content_on_the_page %}
	{% if current_category == 1%}
		<h3>Kategorie: Handys</h3>
	{%endif%}
    <div class="cards">
        <div class="row">
            {% for post in all_posts%}
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    
                    {%if post.image %}
                        <img src="{{post.image}}" class="card-img-top" alt="...">
                    {%else%}
                        <img src="https://fdn.gsmarena.com/imgroot//reviews/18/samsung-galaxy-s9/lifestyle/-728w2/gsmarena_004.jpg" class="card-img-top" alt="...">
                    {%endif%}

                    <div class="card-body">
                        <h5 class="card-title">{{post.post_title}}</h5>

                        <a href="/post/{{post.slug}}" class="btn btn-primary">Post lesen</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <a href="/category/1"><button type="button" class="btn btn-outline-secondary">Anfang</button></a>
    {%for page in pagination%}
        {% if page > 1 and page < last_page %}
            {% if page == current_page %}
                <button type="button" class="btn btn-secondary" disabled>{{page}}</button>
            {%else%}
                <a href="?page={{page}}"><button type="button" class="btn btn-outline-secondary">{{page}}</button></a>
            {%endif%}
        {% endif %}
    {%endfor%}
    <span>...... </span><a href="?page={{last_page}}"><button type="button" class="btn btn-outline-secondary">{{last_page}}</button></a>

{% endblock %}

handys/main_site/templates/main_site/index.html
{% extends 'main_site/base.html' %}
{% load posts_smartphones %}

{%block title%}
<title>Handyvergleich &#8211; und mehr</title>
{%endblock%}

{% block main_content_on_the_page %}
    <h3>Handyvergleich und mehr</h3>
    <div class="cards">
        <div class="row">
            {% for post in posts%}
            <div class="col-md-4 card-col">
                <div class="card" style="width: 18rem;">
                    
                    {% if post.image %}
                        <img src="{{post.image}}" class="card-img-top" alt="...">
                    {% else %}
                        <img src="https://fdn.gsmarena.com/imgroot/reviews/21/samsung-galaxy-a32-5g/lifestyle/-1024w2/gsmarena_006.jpg" class="card-img-top" alt="...">
                    {%endif%}
                
                    <div class="card-body">
                        <h5 class="card-title">{{post.post_title}}</h5>
                        <p class="card-text">{{post.post_content|slice:"200:250"}}</p>
                        <a href="/post/{{post.slug}}" class="btn btn-primary">Post lesen</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="nav2">
        <a href="/"><button type="button" class="btn btn-outline-secondary">Anfang</button></a>
        {%for page in pagination%}
        {% if page > 1 and page < last_page %}
        {% if page == current_page %}
        <button type="button" class="btn btn-secondary"
            disabled>{{page}}</button>
            {%else%}
            <a href="?page={{page}}"><button type="button" class="btn btn-outline-secondary">{{page}}</button></a>
            {%endif%}
            {% endif %}
            {%endfor%}
            <span>...... </span><a href="?page={{last_page}}"><button type="button"
                    class="btn btn-outline-secondary">{{last_page}}</button></a>
    </div>

{% endblock %}

handys/main_site/templates/main_site/list_categories.html
{% for category in cats %}
{%if current_category == category.id%}
    <li><button type="button" class="btn btn-secondary">{{category.name}}</button></li>
{% else %}
    <li><a href="{{category.get_absolute_url}}"><button type="button" class="btn btn-outline-secondary">{{category.name}}</button></a></li>
{% endif %}
{% endfor %}

handys/main_site/templates/main_site/list_of_tags.html
<h5>Populär Handys:</h5>
<div class="tags">
{%for tag in all_tags%}

<a href="/tag/{{tag.tag_name}}"><button type="button" class="btn btn-primary"
        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
        {{tag.tag_name}}
    </button></a>
{%endfor%}
</div>

handys/main_site/templates/main_site/navigation.html
    <div class="nav2">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination pages">
                            <li class="page-item">
                                <a class="page-link" href="/" aria-label="Previous">
                                    <span aria-hidden="true">В начало</span>
                                </a>
                            </li>
                            {% for link in links %}
                                {%if current_category == 1 %}
                                    {%if link == current_page%}
                                        <li class="page-item page-link" style="color: black;">{{link}}</li>
                                    {%else%}
                                        {%if link < last_page%}
                                            <li class="page-item"><a class="page-link" href="/category/{{current_category}}/{{link}}">{{link}}</a></li>
                                        {%endif%}
                                    {%endif%}

                                {%else%}
                                    {%if link == current_page%}
                                        <li class="page-item page-link" style="color: black;">{{link}}</li>
                                    {%else%}
                                        {%if link < last_page%}
                                            <li class="page-item"><a class="page-link" href="/page/{{link}}">{{link}}</a></li>
                                        {%endif%}
                                    {%endif%}
                                {%endif%}
                            {% endfor %}
                            <li class="page-item">
                                {%if current_category%}
                                    <a class="page-link" href="/category/{{current_category}}/{{last_page}}" aria-label="Next">
                                        <span aria-hidden="true">В конец</span>
                                    </a>
                                {%else%}
                                    <a class="page-link" href="/page/{{last_page}}" aria-label="Next">
                                    <span aria-hidden="true">В конец</span>
                                    </a>
                                {%endif%}
                                
                            </li>
                        </ul>
                    </nav>
                </div>

handys/main_site/templates/main_site/other.html
{% extends 'main_site/base.html' %}
{% load posts_smartphones %}
{%block title%}
    <title>Die Vergleiche der Handys = seite {{current_page}}</title>
{%endblock%}
{% block main_content_on_the_page %}
    {% if current_category == 1%}
        <h3>Kategorie: Handys</h3>
    {%else%}
        <h3>Все категории</h3>
    {% endif %}
    <div class="cards">
        <div class="row">
            {% for post in posts%}
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    {% for key, value in images.items %}
                        {% if key == post.slug %}
                            <img src="{{value}}" class="card-img-top" alt="...">
                        {% endif %}
                    {% endfor %}
                    <div class="card-body">
                        <h5 class="card-title">{{post.post_title}}</h5>
                        
                        <a href="/post/{{post.slug}}" class="btn btn-primary">Post lesen</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% if current_category == 0 %}
    {% if current_page %}
    {% navigation current_page=current_page %}
    {% endif %}
    {%else%}
    {% navigation current_page=current_page current_category=current_category %}
    {%endif%}
{% endblock %}

handys/main_site/templates/main_site/post.html
{% extends 'main_site/base.html' %}
{% load posts_smartphones %}

{%block title%}
    <title>{{ content.post_title }}</title>
{%endblock%}

{% block main_content_on_the_page %}

{% autoescape off %}
<h2>{{ content.post_title }}</h2>
<div class="bread">
    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);"
        aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Haupt</li>
            <li class="breadcrumb-item active" aria-current="page">{{content.cat.name}}</li>
        </ol>
    </nav>
    <div>Erschienen: {{content.creation_date | date:"SHORT_DATE_FORMAT"}}</div>
</div>
{{ content.post_content }}
{% endautoescape %}
<div class="prev_">
    <div class="next_previous_posts">
        <div class="prev">
            {%if previous_post%}
                <a href="{{previous_post.slug}}"><button type="button" class="btn btn-secondary">Letzter Post</button>
    </a>
            {%endif%}   
        </div>
        <div class="next">
            {%if next_post%}
                <a href="{{next_post.slug}}"><button type="button" class="btn btn-secondary">Nächster Post</button>
    </a>
            {%endif%}
        </div>
    </div>
</div>
<div class="vergleiche">
    <h4>Andere Vergleiche von dieser Handys</h4>
</div>
<div class="similar_posts">
    
    <div class="row">
                {%for p in similar%}
                <div class="col-xl-4">
                    <div class="card in_similar">
                        {%if p.image%}
                            <img src="{{p.image}}" class="card-img-top" alt="...">
                        {% else %}
                            <img src="https://fdn.gsmarena.com/imgroot/reviews/21/samsung-galaxy-a32-5g/lifestyle/-1024w2/gsmarena_006.jpg" class="card-img-top" alt="...">
                        {%endif%}
                        <div class="card-body">
                            <h5 class="card-title">{{p.post_title}}</h5>
                            <a href="/post/{{p.slug}}" class="btn btn-primary">Post lesen</a>
                        </div>
                    </div>
                </div>
                {%endfor%}
        
    </div>
</div>
{% endblock %}

{%block content_in_right_column%}
    <h5>die Tags des Artikles</h5>
    {%if tag1%}
        <div class="tags"><a href="/tag/{{tag1}}"><button type="button" class="btn btn-primary btn-sm">{{tag1}}</button></a></div>
    {%endif%}
    
    {%if tag2%}
        <div class="tags"><a href="/tag/{{tag2}}"><button type="button" class="btn btn-primary btn-sm">{{tag2}}</button></a></div>
    {%endif%}
    {% list_of_tags %}
{%endblock%}

handys/main_site/templates/main_site/registration.html
{%extends 'main_site/base.html'%}

{%block main_content_on_the_page%}
    {{registragion_form.as_p}}
{%endblock%}

handys/main_site/templates/main_site/tag.html
{% extends 'main_site/base.html' %}
{% load posts_smartphones %}

{%block title%}
    <title>Die Analoga des {{tag}}: was ist besser?</title>
{%endblock%}

{% block main_content_on_the_page %}
<h3>tag: {{tag}}</h3>
<div class="cards">
    <div class="row">
        {% for post in all_posts%}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img src="{{post.image}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{post.post_title}}</h5>

                    <a href="/post/{{post.slug}}" class="btn btn-primary">Post lesen</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

{%block content_in_right_column%}
    {%list_of_tags%}
{%endblock%}